import { Github, Globe, Linkedin, Mail, MapPin, Phone } from "lucide-react";

export const portfolioConfig = {
  personalInfo: {
    name: "Garving Vásquez Severino",
    title: "Desarrollador Fullstack & Analista de Datos",
    email: "garving.vasquez@gmail.com",
    phone: "+1 829 872 5551",
    website: "https://portafolio.gvslabs.cloud/",
    social: [
      {
        name: "GitHub",
        url: "https://github.com/Ghellsing007",
        icon: Github,
      },
      {
        name: "LinkedIn",
        url: "https://www.linkedin.com/in/garving-vasquez-severino-118a98343",
        icon: Linkedin,
      },
      {
        name: "Web",
        url: "https://www.gvslabs.cloud/",
        icon: Globe,
      },
    ],
  },
  es: {
    cvFile: "CV_Garving_Vasquez_Desarrollador_Analista_v2_2025-12.pdf",
    hero: {
      headline: "Transformo ideas en aplicaciones reales.",
      subheadline: "Desarrollador Fullstack y Analista de Datos especializado en crear soluciones digitales.",
      cta: "Ver Proyectos",
    },
    about: {
      title: "Sobre Mí",
      summary: [
        "Soy un apasionado desarrollador con experiencia en la creación de aplicaciones web completas y análisis de datos. Mi enfoque combina habilidades técnicas con una mentalidad orientada a soluciones, permitiéndome construir productos digitales que resuelven problemas reales.",
        "Mi trayectoria me ha llevado a especializarme tanto en el desarrollo frontend con React y Next.js, como en el backend con Node.js y MongoDB. Complemento estas habilidades con análisis de datos utilizando Python, SQL y herramientas de visualización como Power BI.",
      ],
      skillsTitle: "Tecnologías y Herramientas",
      skills: [
        { name: "React", category: "frontend" },
        { name: "Next.js", category: "frontend" },
        { name: "Tailwind CSS", category: "frontend" },
        { name: "Node.js", category: "backend" },
        { name: "Express", category: "backend" },
        { name: "MongoDB", category: "backend" },
        { name: "Python", category: "data" },
        { name: "SQL", category: "data" },
        { name: "Excel", category: "data" },
        { name: "Power BI", category: "data" },
        { name: "Git", category: "tools" },
        { name: "Docker", category: "tools" },
        { name: "Oracle", category: "tools" },
      ],
      languagesTitle: "Idiomas",
      languages: [
        { name: "Español", level: "Nativo" },
        { name: "Inglés", level: "Básico (en proceso de mejora)" },
      ],
    },
    nav: [
      { name: "Inicio", href: "#home" },
      { name: "Sobre Mí", href: "#about" },
      { name: "Proyectos", href: "#projects" },
      { name: "Certificaciones", href: "#certifications" },
      { name: "Currículum", href: "#resume" },
      { name: "Contacto", href: "#contact" },
    ],
    footer: {
      title: "Portafolio",
      subtitle: "Desarrollador Full Stack & Analista de Datos",
      rights: "Todos los derechos reservados",
      quote: "\"El código es poesía en movimiento\"",
    },
    contact: {
      title: "Contacto",
      subtitle: "¿Tienes un proyecto en mente o quieres hablar sobre oportunidades de colaboración? ¡Contáctame!",
      form: {
        name: "Nombre",
        namePlaceholder: "Tu nombre",
        email: "Email",
        emailPlaceholder: "tu.email@ejemplo.com",
        message: "Mensaje",
        messagePlaceholder: "¿En qué puedo ayudarte?",
        submit: "Enviar mensaje",
        submitting: "Enviando...",
        successTitle: "Mensaje enviado",
        successDesc: "Gracias por contactarme. Te responderé pronto.",
        errorTitle: "Error",
        errorDesc: "No se pudo enviar el mensaje. Inténtalo de nuevo.",
      },
      infoTitle: "Información de contacto",
      followTitle: "Sígueme en",
      availability: {
        title: "Disponibilidad",
        description: "Actualmente estoy disponible para proyectos freelance y oportunidades de trabajo a tiempo completo. Mi horario de respuesta es de todos los días, de 8:00 a 19:00 (GMT-5).",
      },
    },
    businessCard: {
      title: "Desarrollador Fullstack & Analista de Datos",
      company: "Freelance / Open to work",
      location: "Santo Domingo, Rep. Dom.",
      tagline: "Transformando datos en decisiones y código en soluciones.",
      skills: ["React", "Next.js", "Node.js", "Python", "SQL", "Power BI"],
    },
    projects: {
      title: "Proyectos",
      subtitle: "Una selección de mis trabajos más recientes y destacados en desarrollo web y análisis de datos.",
      featuredTitle: "Proyecto Destacado",
      viewProject: "Visitar sitio",
      demo: "Demo",
      items: [
        {
          id: 1,
          title: "administrard  ",
          description: "Plataforma para la gestión y administración de negocios. Permite gestionar y administrar los datos de los clientes, los productos y los pedidos.",
          image: "/administrard.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://administrard.gvslabs.cloud/",
          featured: false,
        },
         {
          id: 2,
          title: "Orpheus",
          description: "Plataforma para compartir escuchar y reproducir musica.",
          image: "/orpheus.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API", "MongoDB, PWA"],
          category: "web",
          github: "#",
          demo: "https://orpheus.gvslabs.cloud/",
          featured: true,
        },
        {
          id: 3,
          title: "Rendrly",
          description: "Plataforma para rentar y administrar vehículos.",
          image: "/rendrly.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "mobile",
          github: "#",
          demo: "https://rendrly.netlify.app/",
          featured: false,
        },
        {
          id: 4,
          title: "GVSAnime",
          description: "Web de anime con API de Jikan y diseño moderno.",
          image: "/GVSanime.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://gvsanime.vercel.app/",
          featured: false,
        },
        {
          id: 5,
          title: "Luna Hair & Beauty",
          description: "Page para Luna Hair & Beauty, un salón especializado en coloración y cuidado profesional del cabello en Santo Domingo. El diseño es moderno y atractivo, destacando un fondo de imagen en alta calidad que muestra un servicio de lavado de cabello, lo que transmite profesionalismo y confort.",
          image: "/luna-hair.png",
          tags: ["React", "Vite", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://2-starter.vercel.app/",
          featured: false,
        },
        {
          id: 6,
          title: "Agendly-Saas",
          description: "Plataforma de agendas online para optimizar la atención al cliente y administrar horarios de forma eficiente.",
          image: "/agendly-saas.webp",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://agendly-saas.netlify.app/",
          featured: false,
        },
         {
          id: 7,
          title: "inmoplus",
          description: "Plataforma para la gestión y publicación de inmuebles (bienes raíces). Permite buscar propiedades, agendar visitas y contactar agentes.",
          image: "/inmoplus.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://inmoplus.netlify.app/",
          featured: false,
        },
         {
          id: 8,
          title: "generationqr",
          description: "Generador de códigos QR online.",
          image: "/gvs-QR.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://generationqr.netlify.app/",
          featured: false,
        },
      ]
    },
    certifications: {
      title: "Certificaciones",
      subtitle: "Formación continua y especialización en diferentes áreas del desarrollo y análisis de datos.",
      viewCertificate: "Ver certificado",
      items: [
        {
          id: 1,
          title: "Full Stack Web Development",
          platform: "Universidad de Helsinki",
          date: "2025",
          url: "#",
          category: "web",
        },
        {
          id: 2,
          title: "React.js Professional",
          platform: "Universidad de Helsinki",
          date: "2025",
          url: "#",
          category: "web",
        },
        {
          id: 3,
          title: "Node.js & Express",
          platform: "Universidad de Helsinki",
          date: "2025",
          url: "#",
          category: "backend",
        },
        {
          id: 4,
          title: "MongoDB for Developers",
          platform: "Universidad de Helsinki",
          date: "2025",
          url: "#",
          category: "backend",
        },
        {
          id: 5,
          title: "Data Analysis with Python",
          platform: "Coursera",
          date: "2022",
          url: "#",
          category: "data",
        },
        {
          id: 6,
          title: "SQL Fundamentals",
          platform: "DataCamp",
          date: "2021",
          url: "#",
          category: "data",
        },
        {
          id: 7,
          title: "Power BI Data Analyst",
          platform: "Microsoft Learn",
          date: "2022",
          url: "#",
          category: "data",
        },
        {
          id: 8,
          title: "English B2 Level",
          platform: "Programa de Ingles por Inmersion",
          date: "2025",
          url: "#",
          category: "other",
        },
        {
          id: 9,
          title: "Certified Payroll Configuration C4PN-TPC",
          platform: "Certificación en Cegid Peoplenet",
          date: "2025",
          url: "/20241212_C4PN-TDT_Garving Vásquez Severino.pdf",
          category: "other",
        },
        {
          id: 10,
          title: "Technical Certified Development Tools C4PN-TDT",
          platform: "Certificación en Cegid Peoplenet ",
          date: "2025",
          url: "/20250117_C4PN-TPC_Garving Vásquez Severino.pdf",
          category: "other",
        },
      ]
    },
    resume: {
      title: "Currículum",
      downloadCv: "Descargar CV",
      experienceTitle: "Experiencia",
      educationTitle: "Educación",
      keySkillsTitle: "Habilidades Clave",
      experience: [
        {
          id: 1,
          role: "Programador - Analista",
          company: "SHS Consultores – Mayblue Caribe",
          period: "202X – Presente",
          description:
            "Desarrollo de funcionalidades con LN4 y Oracle SQL, automatización de procesos, soporte técnico y colaboración con el equipo de análisis de datos.",
          skills: ["LN4", "Oracle SQL", "Automatización", "Bases de Datos", "Análisis de Datos"],
        },
        {
          id: 2,
          role: "Desarrollador Full-stack",
          company: "Arkit",
          period: "202X – Presente",
          description:
            "Desarrollo del Backend, API y Devops de Ezploro.",
          skills: ["Arquitectura", "Configuracion de VPS", "Gestión completa"],
        },
        {
          id: 3,
          role: "Soporte Técnico",
          company: "Hogamundi For Sale",
          period: "2018",
          description:
            "Optimización de base de datos MySQL, implementación de respaldos automáticos y mejora de disponibilidad del sistema.",
          skills: ["MySQL", "Optimización de Base de Datos", "Automatización", "Respaldo de Sistemas"],
        },
        {
          id: 4,
          role: "Soporte Informático",
          company: "D’FRANK PC",
          period: "2017",
          description:
            "Desarrollo de página interna con HTML, CSS y JS, mejora de reportes y seguridad de bases de datos.",
          skills: ["HTML", "CSS", "JavaScript", "Desarrollo Web", "Seguridad de Datos"],
        },
      ],
      education: [
        {
          id: 1,
          degree: "Ingeniería en Desarrollo de Software",
          institution: "Universidad Abierta Para Adultos (UAPA)",
          period: "20xx  – presente",
          description: "Especialización en desarrollo de software y análisis de datos.",
        },
        {
          id: 2,
          degree: "Desarrollo Web Full Stack Moderno",
          institution: "Full Stack Open Universidad de Helsinki",
          period: "20xx  – presente",
          description: "Programa intensivo  enfocado en tecnologías web modernas.",
        },
      ],
      keySkills: [
        {
          title: "Desarrollo",
          items: [
            "Desarrollo Full Stack",
            "Arquitectura de Software",
            "Optimización de Rendimiento",
            "Testing y Debugging"
          ]
        },
        {
          title: "Análisis",
          items: [
            "Visualización de Datos",
            "Modelado Estadístico",
            "ETL y Procesamiento",
            "Reportes Automatizados"
          ]
        }
      ]
    },
  },
  en: {
    cvFile: "/CV_Garving_Vasquez_Desarrollador_Analista_v2_2025-12.pdf", // TODO: Update with English CV if available
    hero: {
      headline: "Transforming ideas into real applications.",
      subheadline: "Fullstack Developer and Data Analyst specialized in creating digital solutions.",
      cta: "View Projects",
    },
    about: {
      title: "About Me",
      summary: [
        "I am a passionate developer with experience in creating complete web applications and data analysis. My approach combines technical skills with a solution-oriented mindset, allowing me to build digital products that solve real problems.",
        "My journey has led me to specialize in both frontend development with React and Next.js, and backend with Node.js and MongoDB. I complement these skills with data analysis using Python, SQL, and visualization tools like Power BI.",
      ],
      skillsTitle: "Technologies and Tools",
      skills: [
        { name: "React", category: "frontend" },
        { name: "Next.js", category: "frontend" },
        { name: "Tailwind CSS", category: "frontend" },
        { name: "Node.js", category: "backend" },
        { name: "Express", category: "backend" },
        { name: "MongoDB", category: "backend" },
        { name: "Python", category: "data" },
        { name: "SQL", category: "data" },
        { name: "Excel", category: "data" },
        { name: "Power BI", category: "data" },
        { name: "Git", category: "tools" },
        { name: "Docker", category: "tools" },
        { name: "Oracle", category: "tools" },
      ],
      languagesTitle: "Languages",
      languages: [
        { name: "Spanish", level: "Native" },
        { name: "English", level: "Basic (improving)" },
      ],
    },
    nav: [
      { name: "Home", href: "#home" },
      { name: "About", href: "#about" },
      { name: "Projects", href: "#projects" },
      { name: "Certifications", href: "#certifications" },
      { name: "Resume", href: "#resume" },
      { name: "Contact", href: "#contact" },
    ],
    footer: {
      title: "Portfolio",
      subtitle: "Full Stack Developer & Data Analyst",
      rights: "All rights reserved",
      quote: "\"Code is poetry in motion\"",
    },
    contact: {
      title: "Contact",
      subtitle: "Do you have a project in mind or want to discuss collaboration opportunities? Contact me!",
      form: {
        name: "Name",
        namePlaceholder: "Your name",
        email: "Email",
        emailPlaceholder: "your.email@example.com",
        message: "Message",
        messagePlaceholder: "How can I help you?",
        submit: "Send message",
        submitting: "Sending...",
        successTitle: "Message sent",
        successDesc: "Thanks for contacting me. I'll get back to you soon.",
        errorTitle: "Error",
        errorDesc: "Could not send message. Please try again.",
      },
      infoTitle: "Contact Information",
      followTitle: "Follow me on",
      availability: {
        title: "Availability",
        description: "I am currently available for freelance projects and full-time job opportunities. My response hours are every day, from 8:00 to 19:00 (GMT-5).",
      },
    },
    businessCard: {
      title: "Fullstack Developer & Data Analyst",
      company: "Freelance / Open to work",
      location: "Santo Domingo, Dom. Rep.",
      tagline: "Transforming data into decisions and code into solutions.",
      skills: ["React", "Next.js", "Node.js", "Python", "SQL", "Power BI"],
    },
    projects: {
      title: "Projects",
      subtitle: "A selection of my most recent and outstanding work in web development and data analysis.",
      featuredTitle: "Featured Project",
      viewProject: "Visit site",
      demo: "Demo",
      items: [
        {
          id: 1,
          title: "Orpheus",
          description: "Platform to share, listen, and play music.",
          image: "/orpheus-music.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://orpheus-music-sand.vercel.app/",
          featured: true,
        },
        {
          id: 2,
          title: "Rendrly",
          description: "Platform to rent and manage vehicles.",
          image: "/rendrly.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "mobile",
          github: "#",
          demo: "https://rendrly.netlify.app/",
          featured: false,
        },
        {
          id: 3,
          title: "GVSAnime",
          description: "Anime website with Jikan API and modern design.",
          image: "/GVSanime.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://gvsanime.vercel.app/",
          featured: false,
        },
        {
          id: 4,
          title: "Luna Hair & Beauty",
          description: "Page for Luna Hair & Beauty, a salon specialized in hair coloring and professional care in Santo Domingo. The design is modern and attractive, highlighting a high-quality background image showing a hair washing service, conveying professionalism and comfort.",
          image: "/luna-hair.png",
          tags: ["React", "Vite", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://2-starter.vercel.app/",
          featured: false,
        },
        {
          id: 5,
          title: "Agendly-Saas",
          description: "Online agenda platform to optimize customer service and manage schedules efficiently.",
          image: "/agendly-saas.webp",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://agendly-saas.netlify.app/",
          featured: false,
        },
        {
          id: 6,
          title: "inmoplus",
          description: "Platform for real estate management and publication. Allows searching properties, scheduling visits, and contacting agents.",
          image: "/inmoplus.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://inmoplus.netlify.app/",
          featured: false,
        },
        {
          id: 7,
          title: "generationqr",
          description: "Online QR code generator.",
          image: "/gvs-QR.png",
          tags: ["React", "Next.js", "Tailwind CSS", "API"],
          category: "web",
          github: "#",
          demo: "https://inmoplus.netlify.app/",
          featured: false,
        },
      ]
    },
    certifications: {
      title: "Certifications",
      subtitle: "Continuous training and specialization in different areas of development and data analysis.",
      viewCertificate: "View certificate",
      items: [
        {
          id: 1,
          title: "Full Stack Web Development",
          platform: "University of Helsinki",
          date: "2025",
          url: "#",
          category: "web",
        },
        {
          id: 2,
          title: "React.js Professional",
          platform: "University of Helsinki",
          date: "2025",
          url: "#",
          category: "web",
        },
        {
          id: 3,
          title: "Node.js & Express",
          platform: "University of Helsinki",
          date: "2025",
          url: "#",
          category: "backend",
        },
        {
          id: 4,
          title: "MongoDB for Developers",
          platform: "University of Helsinki",
          date: "2025",
          url: "#",
          category: "backend",
        },
        {
          id: 5,
          title: "Data Analysis with Python",
          platform: "Coursera",
          date: "2022",
          url: "#",
          category: "data",
        },
        {
          id: 6,
          title: "SQL Fundamentals",
          platform: "DataCamp",
          date: "2021",
          url: "#",
          category: "data",
        },
        {
          id: 7,
          title: "Power BI Data Analyst",
          platform: "Microsoft Learn",
          date: "2022",
          url: "#",
          category: "data",
        },
        {
          id: 8,
          title: "English B2 Level",
          platform: "English Immersion Program",
          date: "2025",
          url: "#",
          category: "other",
        },
        {
          id: 9,
          title: "Certified Payroll Configuration C4PN-TPC",
          platform: "Cegid Peoplenet Certification",
          date: "2025",
          url: "/20241212_C4PN-TDT_Garving Vásquez Severino.pdf",
          category: "other",
        },
        {
          id: 10,
          title: "Technical Certified Development Tools C4PN-TDT",
          platform: "Cegid Peoplenet Certification",
          date: "2025",
          url: "/20250117_C4PN-TPC_Garving Vásquez Severino.pdf",
          category: "other",
        },
      ]
    },
    resume: {
      title: "Resume",
      downloadCv: "Download CV",
      experienceTitle: "Experience",
      educationTitle: "Education",
      keySkillsTitle: "Key Skills",
      experience: [
        {
          id: 1,
          role: "Programmer - Analyst",
          company: "SHS Consultores – Mayblue Caribe",
          period: "202X – Present",
          description:
            "Development of functionalities with LN4 and Oracle SQL, process automation, technical support, and collaboration with the data analysis team.",
          skills: ["LN4", "Oracle SQL", "Automation", "Databases", "Data Analysis"],
        },
        {
          id: 2,
          role: "Full-stack Developer",
          company: "Arkit",
          period: "202X – Present",
          description:
            "Backend development, API, and DevOps for Ezploro.",
          skills: ["Architecture", "VPS Configuration", "Full Management"],
        },
        {
          id: 3,
          role: "Technical Support",
          company: "Hogamundi For Sale",
          period: "2018",
          description:
            "MySQL database optimization, implementation of automatic backups, and system availability improvement.",
          skills: ["MySQL", "Database Optimization", "Automation", "System Backups"],
        },
        {
          id: 4,
          role: "IT Support",
          company: "D’FRANK PC",
          period: "2017",
          description:
            "Development of internal page with HTML, CSS, and JS, improvement of reports and database security.",
          skills: ["HTML", "CSS", "JavaScript", "Web Development", "Data Security"],
        },
      ],
      education: [
        {
          id: 1,
          degree: "Software Development Engineering",
          institution: "Open University for Adults (UAPA)",
          period: "20xx  – present",
          description: "Specialization in software development and data analysis.",
        },
        {
          id: 2,
          degree: "Modern Full Stack Web Development",
          institution: "Full Stack Open University of Helsinki",
          period: "20xx  – present",
          description: "Intensive program focused on modern web technologies.",
        },
      ],
      keySkills: [
        {
          title: "Development",
          items: [
            "Full Stack Development",
            "Software Architecture",
            "Performance Optimization",
            "Testing and Debugging"
          ]
        },
        {
          title: "Analysis",
          items: [
            "Data Visualization",
            "Statistical Modeling",
            "ETL and Processing",
            "Automated Reporting"
          ]
        }
      ]
    },
  },
} as const;
